### PR TITLE
Update 0712-query-params-as-derived-data.md

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
I would love this change, but afaict, that `queryParams` array is required :(

**Comment by knownasilya** [comment]
Ah, I thought it was a typo

**Comment by NullVoxPopuli** [comment]
yeah :(

I could do a separate RFC exploring getting rid of that entirely though :)

**Comment by NullVoxPopuli** [comment]
I think it's doable, but would opt you out of all the configuration and stuff that controllers currently have

**Pull request closed without merging**
